### ISSUE TITLE
Remove pinning

### ISSUE THREAD

**Issue by fabaff** [jimmyd-be/Renson-endura-delta-library#11]
Most dependencies are pinned. 

https://github.com/jimmyd-be/Renson-ventilation-library/blob/32908bd32975629bfc4d723415e2ef3f3235c5ec/setup.py#L20-L22

E.g., `pytest` is set to a 2.5 years old release.

Distributions often ship different releases. Home Assistant also want different releases. 

Please remove the pinning or replace it with constraints where needed.

**Comment by jimmyd-be** [comment]
I changed most of them to this or a newer version.
