### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by fabaff** [jimmyd-be/Renson-endura-delta-library#13]
Please follow [PEP-8](https://www.python.org/dev/peps/pep-0008/#naming-conventions) for naming.

Especially the module name (`rensonVentilationLib`). Now it's easy to change as the Home Assistant integration is under review and distribution haven't started to this module as package.

**Comment by jimmyd-be** [comment]
Renamed project, modules, files, variables to use a more logical name + pep8
