### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [jimmyd-be/Renson-endura-delta-library#14]
It would be very helpful if you could tag releases as well. This would enable distributions to fetch the source from GitHub instead of PyPI.

PyPI: 1.2.1
GitHub: 1.1.1 (https://github.com/jimmyd-be/Renson-ventilation-library/tags)

Thanks

**Comment by jimmyd-be** [comment]
I misted that one. I normally tag always my release. Fixed that now.
